name: find_dropdown
description: Simple and robust FindDropdown with item search feature, making it possible to use an offline item list or filtering URL for easy customization.
version: 1.0.0
homepage: https://flutterando.com.br/
git: https://github.com/davidsdearaujo/find_dropdown
repository: https://github.com/davidsdearaujo/find_dropdown

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  select_dialog: ^2.0.0
  flutter:
    sdk: flutter

# dependency_overrides:
#   select_dialog: 
#     git:
#       url: https://github.com/davidsdearaujo/select_dialog.git
#   select_dialog:
#     path: C:\projects\packages\select_dialog


dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
